### ISSUE TITLE
vle.extension.dsdevs does not compile in mode Debug with vle2.0

### ISSUE THREAD

**Issue by Chabrier** [Chabrier/packages#7]
DSDevs.cpp:50:17: error: invalid use of incomplete type ‘const struct vle::devs::ExecutiveInit’
     assert(model.model().getParent());

and,

Executive.hpp:63:8: note: forward declaration of ‘struct vle::devs::ExecutiveInit’
 struct ExecutiveInit;
